### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by BlueBeN82** [alex-tomin/Tomin.Tools.KioskMode#4]
Windows are not moved in Windows 10. Fullscreen is not working as well.

```
Der Typ [Tomin.Tools.KioskMode.Enums.ShowWindowCommands] wurde nicht gefunden.
In C:\KioskMode\HelperFunctions.ps1:43 Zeichen:34
+ ... dow($window, [Tomin.Tools.KioskMode.Enums.ShowWindowCommands]::Restor ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Tomin.Tools.Kio...wWindowCommands:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In C:\KioskMode\HelperFunctions.ps1:44 Zeichen:5
+     $Helpers::MoveToMonitor($window, $MonitorNum)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In C:\KioskMode\HelperFunctions.ps1:45 Zeichen:5
+     $Helpers::SendKey($window, '{F11}')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

Any ideas how to fix this?

**Comment by Sysa** [comment]
Looks like we should fix it ourselves :)

**Comment by Sysa** [comment]
if you can use chrome, check this: https://github.com/ControlExpert/chrome-multiwindow-positioner
this is not really depends on platform you use.

**Comment by ThomasRunting** [comment]
@Sysa Download the code and rebuild the sln on windows 10.
I just did that with vscode 2017 and it now works.
also change the target to 4.6.1

**Comment by SteveDevOps** [comment]
@ThomasRunting  I did exactly that but still getting (rebuilt using vs 2017 and targeted 4.6.1)  --
Add-Type: Could not load file or assembly 'file:///c:\kiosk-mode\Tomin.Tools.KioskMode.dll' or one of its dependencies

and then upon further inspection.. it can't find the type Tomin.Tools.KioskMode.WinApi 
What am I missing?

**Comment by SteveDevOps** [comment]
Nevermind.. had to unblock. :)

ref: https://d-fens.ch/2014/08/02/nobrainer-powershell-fails-to-add-type-an-assembly-with-hresult-0x80131515/

**Comment by boonkim** [comment]
I try this and work for Windows 10 

Step 1 
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

Step 2 
Right Click Tomin.Tools.KioskMode.dll And Checked Unblock 

Step 3 
Create Short cut Like this 
powershell.exe -noexit -ExecutionPolicy Bypass -File c:\Kiosk-Mode\<your_file_name>.ps1 

It work!
